export const ADD_PRODUCT_BASKET = "ADD_PRODUCT_BASKET";
export const GET_NUMBER_BASKET = "GET_NUMBER_BASKET";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANITIY = "DECREASE_QUANITIY";
